# name of the program (Minix service)
PROG=lab5

# source files
SRCS = lab5.c video.c utils.c

# compilation flags
CFLAGS += -pedantic
CFLAGS += -DLAB5

# LCF library
DPADD += ${LIBLCF}
LDADD += -llcf

.include <minix.lcom.mk>
